[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "axioschain"
authors = [{name = "Nicolas Cloutier", email = "nicolas.cloutier78@gmail.com"}]
dynamic = ["version", "description"]
